import { app, BrowserWindow, nativeImage, screen } from "electron";
import getResourcePath from "@/common/get-resource-path";
import { IWindowEvents, IWindowManager } from "@/types/main/window-manager";
import { localPluginName, PlayerState, ResourceName } from "@/common/constant";
import voidCallback from "@/common/void-callback";
import ThumbBarUtil from "@/common/thumb-bar-util";
import EventEmitter from "eventemitter3";
import WindowDrag from "@shared/window-drag/main";
import AppConfig from "@shared/app-config/main";
import messageBus from "@shared/message-bus/main";
import { IAppConfig } from "@/types/app-config";
import debounce from "@/common/debounce";


// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const LRC_WINDOW_WEBPACK_ENTRY: string;
declare const LRC_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const MINIMODE_WINDOW_WEBPACK_ENTRY: string;
declare const MINIMODE_WINDOW_PRELOAD_WEBPACK_ENTRY: string;


class WindowManager implements IWindowManager {
    private static mainWindow: BrowserWindow | null = null;
    private static lrcWindow: BrowserWindow | null = null;
    private static miniModeWindow: BrowserWindow | null = null;

    private ee: EventEmitter = new EventEmitter();

    getMainWindow(): BrowserWindow {
        return WindowManager.mainWindow;
    }

    get mainWindow() {
        return WindowManager.mainWindow;
    }

    get lyricWindow() {
        return WindowManager.lrcWindow;
    }

    get miniModeWindow() {
        return WindowManager.miniModeWindow;
    }

    getExtensionWindows(): BrowserWindow[] {
        const extWindows = [];
        if (WindowManager.lrcWindow) {
            extWindows.push(WindowManager.lrcWindow);
        }
        if (WindowManager.miniModeWindow) {
            extWindows.push(WindowManager.miniModeWindow);
        }
        return extWindows;
    }

    getAllWindows(): BrowserWindow[] {
        const windows = [];
        if (WindowManager.mainWindow) {
            windows.push(WindowManager.mainWindow);
        }
        if (WindowManager.lrcWindow) {
            windows.push(WindowManager.lrcWindow);
        }
        if (WindowManager.miniModeWindow) {
            windows.push(WindowManager.miniModeWindow);
        }
        return windows;
    }

    private emit<T extends keyof IWindowEvents>(event: T, data: IWindowEvents[T]) {
        this.ee.emit(event, data);
    }

    public on<T extends keyof IWindowEvents>(event: T, listener: (data: IWindowEvents[T]) => void) {
        this.ee.on(event, listener);
    }

    /**************************** Main Window ***************************/
    private createMainWindow() {
        // 娓呯悊鏃х獥鍙?
        if (WindowManager.mainWindow) {
            WindowManager.mainWindow.removeAllListeners();
            if (!WindowManager.mainWindow.isDestroyed()) {
                WindowManager.mainWindow.close();
                WindowManager.mainWindow.destroy();
            }
            WindowManager.mainWindow = null;
        }
        // 1. 鍒涘缓涓荤獥鍙?
        const initSize = AppConfig.getConfig("private.mainWindowSize");
        const mainWindow = new BrowserWindow({
            height: initSize?.height ?? 700,
            width: initSize?.width ?? 1050,
            minHeight: 700,
            minWidth: 1050,
            webPreferences: {
                preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
                nodeIntegration: true,
                nodeIntegrationInWorker: true,
                contextIsolation: false,
                webSecurity: false,
                sandbox: false,
                webviewTag: true,
            },
            frame: false,
            icon: nativeImage.createFromPath(getResourcePath(ResourceName.LOGO_IMAGE)),
        });

        const updateWindowSizeConfig = debounce(() => {
            const [wWidth, wHeight] = mainWindow.getSize();
            AppConfig.setConfig({
                "private.mainWindowSize": {
                    width: wWidth,
                    height: wHeight,
                },
            });
        }, 300, {
            leading: false,
            trailing: true,
        });
        mainWindow.on("resize", updateWindowSizeConfig);

        // 2. 鍔犺浇涓荤晫闈?
        const initUrl = new URL(MAIN_WINDOW_WEBPACK_ENTRY);
        initUrl.hash = `/main/musicsheet/${localPluginName}/favorite`;
        mainWindow.loadURL(initUrl.toString()).then(voidCallback);

        // 3. 寮€鍙戣€呭伐鍏?
        if (!app.isPackaged) {
            mainWindow.on("ready-to-show", () => {
                mainWindow.webContents.openDevTools();
            });
        }

        // 4. 涓荤獥鍙ttp hack閫昏緫
        mainWindow.webContents.session.webRequest.onBeforeSendHeaders(
            (details, callback) => {
                /** hack headers */
                try {
                    const url = new URL(details.url);
                    const setHeadersOptions = url.searchParams.get("_setHeaders");
                    if (!setHeadersOptions) {
                        throw new Error("No Need To Hack");
                    }
                    const originalRequestHeaders = details.requestHeaders ?? {};
                    let requestHeaders: Record<string, string> = {};
                    if (setHeadersOptions) {
                        const decodedHeaders = JSON.parse(
                            decodeURIComponent(setHeadersOptions),
                        );
                        for (const k in originalRequestHeaders) {
                            requestHeaders[k.toLowerCase()] = originalRequestHeaders[k];
                        }
                        for (const k in decodedHeaders) {
                            requestHeaders[k.toLowerCase()] = decodedHeaders[k];
                        }
                    } else {
                        requestHeaders = details.requestHeaders;
                    }
                    callback({
                        requestHeaders,
                    });
                } catch {
                    callback({
                        requestHeaders: details.requestHeaders,
                    });
                }
            },
        );

        mainWindow.on("close", (e) => {
            if (process.platform === "win32" && AppConfig.getConfig("normal.closeBehavior") === "minimize") {
                e.preventDefault();
                mainWindow.hide();
                mainWindow.setSkipTaskbar(true);
            }
        });

        // 5. 鏇存柊thumbbar
        ThumbBarUtil.setThumbBarButtons(mainWindow, false);
        WindowManager.mainWindow = mainWindow;

        // 6. 鍙戝嚭淇″彿
        this.emit("WindowCreated", {
            windowName: "main",
            browserWindow: mainWindow,
        });
    }

    public showMainWindow() {
        if (!WindowManager.mainWindow || WindowManager.mainWindow.isDestroyed()) {
            this.createMainWindow();
        }

        const mainWindow = WindowManager.mainWindow;

        if (mainWindow.isMinimized()) {
            mainWindow.restore();
        } else if (mainWindow.isVisible()) {
            mainWindow.focus();
        } else {
            mainWindow.show();
        }
        mainWindow.moveTop();
        mainWindow.setSkipTaskbar(false);

        if (process.platform === "win32") {
            const appState = messageBus.getAppState();
            ThumbBarUtil.setThumbBarButtons(mainWindow, appState.playerState === PlayerState.Playing);
        }
    }

    public closeMainWindow() {
        WindowManager.mainWindow.close();
        WindowManager.mainWindow = null;
    }

    /**************************** Lyric Window ***************************/
    private static lyricWindowMinSize: ICommon.ISize = {
        width: 520,
        height: 120,
    };
    private static lyricWindowMaxSize: ICommon.ISize = {
        width: Infinity,
        height: Infinity,
    };

    private formatLyricWindowSize(width?: number, height?: number): ICommon.ISize {
        return {
            width: Math.min(Math.max(width ?? Infinity, WindowManager.lyricWindowMinSize.width), WindowManager.lyricWindowMaxSize.width),
            height: Math.min(Math.max(height ?? Infinity, WindowManager.lyricWindowMinSize.height), WindowManager.lyricWindowMaxSize.height),
        };
    }


    private createLyricWindow() {
        const initPosition = AppConfig.getConfig("private.lyricWindowPosition");
        const initSize = AppConfig.getConfig("private.lyricWindowSize");
        const display = initPosition
            ? screen.getDisplayNearestPoint(initPosition)
            : screen.getPrimaryDisplay();

        WindowManager.lyricWindowMaxSize.width = display.workArea.width;
        WindowManager.lyricWindowMaxSize.height = display.workArea.height;

        const isLegacyBubbleWindow = !!initSize && initSize.width <= 560 && initSize.height <= 180;
        let {
            width,
            height,
        } = this.formatLyricWindowSize(
            isLegacyBubbleWindow ? 900 : (initSize?.width ?? 900),
            isLegacyBubbleWindow ? 180 : (initSize?.height ?? 180),
        );

        const lyricWindow = new BrowserWindow({
            height,
            width,
            x: initPosition?.x,
            y: initPosition?.y,
            transparent: true,
            backgroundColor: "#00000000",
            webPreferences: {
                preload: LRC_WINDOW_PRELOAD_WEBPACK_ENTRY,
                nodeIntegration: true,
                contextIsolation: false,
                webSecurity: false,
                sandbox: false,
            },
            minWidth: WindowManager.lyricWindowMinSize.width,
            minHeight: WindowManager.lyricWindowMinSize.height,
            maxWidth: WindowManager.lyricWindowMaxSize.width,
            maxHeight: WindowManager.lyricWindowMaxSize.height,
            resizable: true,
            frame: false,
            skipTaskbar: true,
            alwaysOnTop: true,
            icon: nativeImage.createFromPath(getResourcePath(ResourceName.LOGO_IMAGE)),
        });

        lyricWindow.setMaximumSize(WindowManager.lyricWindowMaxSize.width, WindowManager.lyricWindowMaxSize.height);

        // and load the index.html of the app.
        lyricWindow.loadURL(LRC_WINDOW_WEBPACK_ENTRY);

        if (!app.isPackaged) {
            // Open the DevTools.
            lyricWindow.webContents.openDevTools();
        }

        const updateCallback = (_patch: IAppConfig, _: any, _from: "main" | "renderer") => {
            const [nextWidth, nextHeight] = lyricWindow.getSize();
            width = nextWidth;
            height = nextHeight;
        };
        const savePositionConfig = () => {
            if (lyricWindow.isDestroyed()) {
                return;
            }
            const [x, y] = lyricWindow.getPosition();
            AppConfig.setConfig({
                "private.lyricWindowPosition": {
                    x,
                    y,
                },
            });
        };
        const updatePositionConfig = debounce(savePositionConfig, 300, {
            leading: false,
            trailing: true,
        });
        AppConfig.onConfigUpdated(updateCallback);
        lyricWindow.on("close", () => {
            updatePositionConfig.cancel();
            savePositionConfig();
        });
        lyricWindow.on("closed", () => {
            updatePositionConfig.cancel();
            AppConfig.offConfigUpdated(updateCallback);
        });


        lyricWindow.on("resize", () => {
            const [wWidth, wHeight] = lyricWindow.getSize();
            width = wWidth;
            height = wHeight;
            AppConfig.setConfig({
                "private.lyricWindowSize": {
                    width: wWidth,
                    height: wHeight,
                },
            });
        });

        lyricWindow.on("move", updatePositionConfig);
        if (process.platform !== "darwin") {
            lyricWindow.on("moved", savePositionConfig);
        }
        // 鍒濆鍖栬缃?
        lyricWindow.once("ready-to-show", async () => {
            const position = AppConfig.getConfig("private.lyricWindowPosition");
            if (position) {
                this.normalizeWindowPosition(lyricWindow, position, async (position) => {
                    AppConfig.setConfig({
                        "private.lyricWindowPosition": position,
                    });
                });
            }

            const lockState = AppConfig.getConfig("lyric.lockLyric");

            if (lockState) {
                lyricWindow.setIgnoreMouseEvents(true, {
                    forward: true,
                });
            }
        });

        if (process.platform === "darwin") {
            // @ts-ignore ignore error in windows legacy
            lyricWindow.invalidateShadow();
        }

        WindowManager.lrcWindow = lyricWindow;
        this.emit("WindowCreated", {
            windowName: "lyric",
            browserWindow: lyricWindow,
        });
    }


    public showLyricWindow() {
        if (!WindowManager.lrcWindow) {
            this.createLyricWindow();
        }

        const lrcWindow = WindowManager.lrcWindow;

        lrcWindow.show();
        AppConfig.setConfig({
            "lyric.enableDesktopLyric": true,
        });

    }

    public closeLyricWindow() {
        const lyricWindow = WindowManager.lrcWindow;
        if (lyricWindow && !lyricWindow.isDestroyed()) {
            const [x, y] = lyricWindow.getPosition();
            AppConfig.setConfig({
                "private.lyricWindowPosition": {
                    x,
                    y,
                },
            });
            lyricWindow.close();
        }
        WindowManager.lrcWindow = null;
        AppConfig.setConfig({
            "lyric.enableDesktopLyric": false,
        });
    }

    /**************************** MiniMode Window ***************************/
    private createMiniModeWindow() {
        // Create the browser window.
        const width = 428;
        const height = 92;
        const initPosition = AppConfig.getConfig("private.minimodeWindowPosition");

        const miniWindow = new BrowserWindow({
            height,
            width,
            x: initPosition?.x,
            y: initPosition?.y,
            webPreferences: {
                preload: MINIMODE_WINDOW_PRELOAD_WEBPACK_ENTRY,
                nodeIntegration: true,
                nodeIntegrationInWorker: true,
                contextIsolation: false,
                webSecurity: false,
                sandbox: false,
            },
            show: false,
            resizable: false,
            frame: false,
            skipTaskbar: true,
            alwaysOnTop: true,
            transparent: true,
            backgroundColor: "#00000000",
            maximizable: false,
            minimizable: false,
            fullscreenable: false,
        });

        // and load the index.html of the app.
        const initUrl = new URL(MINIMODE_WINDOW_WEBPACK_ENTRY);
        miniWindow.loadURL(initUrl.toString());

        if (!app.isPackaged) {
            miniWindow.on("ready-to-show", () => {
                // Open the DevTools.
                miniWindow.webContents.openDevTools();
            });
        }

        WindowDrag.setWindowDraggable(miniWindow, {
            width,
            height,
            onDragEnd(point) {
                AppConfig.setConfig({
                    "private.minimodeWindowPosition": point,
                });
            },
        });

        miniWindow.once("ready-to-show", () => {
            const position = AppConfig.getConfig("private.minimodeWindowPosition");
            if (position) {
                this.normalizeWindowPosition(miniWindow, position, async (position) => {
                    AppConfig.setConfig({
                        "private.minimodeWindowPosition": position,
                    });
                });
            }

        });
        WindowManager.miniModeWindow = miniWindow;
        this.emit("WindowCreated", {
            windowName: "minimode",
            browserWindow: miniWindow,
        });
    }

    public showMiniModeWindow() {
        if (!WindowManager.miniModeWindow) {
            this.createMiniModeWindow();
        }

        const miniWindow = WindowManager.miniModeWindow;

        if (miniWindow.isMinimized()) {
            miniWindow.restore();
        } else if (miniWindow.isVisible()) {
            miniWindow.focus();
        } else {
            miniWindow.show();
        }
        miniWindow.moveTop();
        miniWindow.setSkipTaskbar(true);
        AppConfig.setConfig({
            "private.minimode": true,
        });
    }


    public closeMiniModeWindow() {
        WindowManager.miniModeWindow?.close();
        WindowManager.miniModeWindow = null;
        AppConfig.setConfig({
            "private.minimode": false,
        });
    }

    private normalizeWindowPosition(window: BrowserWindow, position: ICommon.IPoint, onNormalized: (position: ICommon.IPoint) => void) {
        const currentDisplayBounds =
            screen.getDisplayNearestPoint(position).bounds;
        const windowBounds = window.getBounds();
        // 濡傛灉瀹屽叏鍦ㄦ槸绐楀锛岄噸缃綅缃?
        const [left, top, right, bottom] = [
            position.x,
            position.y,
            position.x + windowBounds.width,
            position.y + windowBounds.height,
        ];
        let needMakeup = false;
        if (left > currentDisplayBounds.x + currentDisplayBounds.width) {
            position.x =
                currentDisplayBounds.x + currentDisplayBounds.width - windowBounds.width;
            needMakeup = true;
        } else if (right < currentDisplayBounds.x) {
            position.x = currentDisplayBounds.x;
            needMakeup = true;
        }
        if (top > currentDisplayBounds.y + currentDisplayBounds.height) {
            position.y =
                currentDisplayBounds.y + currentDisplayBounds.height - windowBounds.height;
            needMakeup = true;
        } else if (bottom < currentDisplayBounds.y) {
            position.y = currentDisplayBounds.y;
            needMakeup = true;
        }
        window.setPosition(position.x, position.y, false);
        if (needMakeup) {
            onNormalized(position);
        }
    }
}


export default new WindowManager();



