import { app, BrowserWindow, nativeImage, screen } from "electron";
import getResourcePath from "@/common/get-resource-path";
import { IWindowEvents, IWindowManager } from "@/types/window-manager";
import { isPlaybackActive, localPluginName, ResourceName } from "@/common/constant";
import voidCallback from "@/common/void-callback";
import ThumbBarUtil from "@/common/thumb-bar-util";
import EventEmitter from "eventemitter3";
import AppConfig from "@shared/app-config/main";
import messageBus from "@shared/message-bus/main";
import debounce from "@/common/debounce";
import logger from "@shared/logger/main";
import { toError } from "@/common/error-util";
import { isFullscreenApplicationRunning } from "./fullscreen-notification-state";
import { isFullscreenForegroundWindow } from "./foreground-fullscreen-state";
import { hardenWindow } from "@main/electron-security";
import { getInitialWindowSurfaceOptions } from "@shared/themepack/window-material";
import { fileURLToPath } from "url";


// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).

declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const LRC_WINDOW_WEBPACK_ENTRY: string;
declare const LRC_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
declare const MINIMODE_WINDOW_WEBPACK_ENTRY: string;
declare const MINIMODE_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

function loadRendererEntry(
    targetWindow: BrowserWindow,
    entry: string,
    hash?: string,
) {
    const entryUrl = new URL(entry);
    if (app.isPackaged && entryUrl.protocol === "file:") {
        // loadFile resolves through app.getAppPath(), including app.asar. This
        // keeps renderer navigation inside the application archive when the
        // OnlyLoadAppFromAsar fuse is enabled.
        return targetWindow.loadFile(fileURLToPath(entryUrl), { hash });
    }
    if (hash) {
        entryUrl.hash = hash;
    }
    return targetWindow.loadURL(entryUrl.toString());
}


class WindowManager implements IWindowManager {
    private static lyricWindowZOrderPollInterval = 1000;
    private static mainWindow: BrowserWindow | null = null;
    private static lrcWindow: BrowserWindow | null = null;
    private static miniModeWindow: BrowserWindow | null = null;

    private ee: EventEmitter = new EventEmitter();
    private repaintingTransparentWindows = new WeakSet<BrowserWindow>();
    private lyricWindowZOrderMonitor: NodeJS.Timeout | null = null;
    private auxiliaryWindowVisibilityBeforeImmersive: {
        lyric: boolean;
        minimode: boolean;
    } | null = null;

    getMainWindow(): BrowserWindow {
        if (!WindowManager.mainWindow || WindowManager.mainWindow.isDestroyed()) {
            this.createMainWindow();
        }
        if (!WindowManager.mainWindow) {
            throw new Error("Main window is not available");
        }
        return WindowManager.mainWindow;
    }

    get mainWindow() {
        return WindowManager.mainWindow;
    }

    get lyricWindow() {
        return WindowManager.lrcWindow;
    }

    get miniModeWindow() {
        return WindowManager.miniModeWindow;
    }

    getExtensionWindows(): BrowserWindow[] {
        const extWindows = [];
        if (WindowManager.lrcWindow) {
            extWindows.push(WindowManager.lrcWindow);
        }
        if (WindowManager.miniModeWindow) {
            extWindows.push(WindowManager.miniModeWindow);
        }
        return extWindows;
    }

    getAllWindows(): BrowserWindow[] {
        const windows = [];
        if (WindowManager.mainWindow) {
            windows.push(WindowManager.mainWindow);
        }
        if (WindowManager.lrcWindow) {
            windows.push(WindowManager.lrcWindow);
        }
        if (WindowManager.miniModeWindow) {
            windows.push(WindowManager.miniModeWindow);
        }
        return windows;
    }

    public setAuxiliaryWindowsSuppressed(suppressed: boolean) {
        if (suppressed) {
            if (this.auxiliaryWindowVisibilityBeforeImmersive) {
                return;
            }

            const lyricWindow = WindowManager.lrcWindow;
            const miniModeWindow = WindowManager.miniModeWindow;
            this.auxiliaryWindowVisibilityBeforeImmersive = {
                lyric: Boolean(
                    lyricWindow
                    && !lyricWindow.isDestroyed()
                    && lyricWindow.isVisible(),
                ),
                minimode: Boolean(
                    miniModeWindow
                    && !miniModeWindow.isDestroyed()
                    && miniModeWindow.isVisible(),
                ),
            };
            if (lyricWindow && !lyricWindow.isDestroyed()) {
                lyricWindow.hide();
            }
            if (miniModeWindow && !miniModeWindow.isDestroyed()) {
                miniModeWindow.hide();
            }
            return;
        }

        const restore = this.auxiliaryWindowVisibilityBeforeImmersive;
        if (!restore) {
            return;
        }
        this.auxiliaryWindowVisibilityBeforeImmersive = null;
        if (restore.lyric) {
            const lyricWindow = WindowManager.lrcWindow;
            if (lyricWindow && !lyricWindow.isDestroyed()) {
                if (process.platform === "win32") {
                    this.syncLyricWindowZOrder(lyricWindow);
                }
                lyricWindow.setBackgroundColor("#00000000");
                lyricWindow.showInactive();
                this.repaintTransparentWindowAfterShow(lyricWindow);
            } else {
                this.showLyricWindow();
            }
        }
        if (restore.minimode) {
            const miniModeWindow = WindowManager.miniModeWindow;
            if (miniModeWindow && !miniModeWindow.isDestroyed()) {
                miniModeWindow.showInactive();
                miniModeWindow.moveTop();
                miniModeWindow.setSkipTaskbar(true);
            } else {
                this.showMiniModeWindow();
            }
        }
    }

    private emit<T extends keyof IWindowEvents>(event: T, data: IWindowEvents[T]) {
        this.ee.emit(event, data);
    }

    public on<T extends keyof IWindowEvents>(event: T, listener: (data: IWindowEvents[T]) => void) {
        this.ee.on(event, listener);
    }

    /**************************** Main Window ***************************/
    private createMainWindow() {
        // 清理旧窗口
        if (WindowManager.mainWindow) {
            WindowManager.mainWindow.removeAllListeners();
            if (!WindowManager.mainWindow.isDestroyed()) {
                WindowManager.mainWindow.close();
                WindowManager.mainWindow.destroy();
            }
            WindowManager.mainWindow = null;
        }
        // 1. 创建主窗口
        const initSize = AppConfig.getConfig("private.mainWindowSize");
        const mainWindow = new BrowserWindow({
            height: initSize?.height ?? 700,
            width: initSize?.width ?? 1050,
            minHeight: 700,
            minWidth: 1050,
            webPreferences: {
                preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
                nodeIntegration: false,
                nodeIntegrationInWorker: false,
                contextIsolation: true,
                webSecurity: true,
                allowRunningInsecureContent: false,
                sandbox: true,
                webviewTag: false,
                navigateOnDragDrop: false,
            },
            frame: false,
            // DWM Acrylic owns backdrop translucency. Keep the BrowserWindow
            // non-layered so the resizable main window remains stable on 24H2.
            ...getInitialWindowSurfaceOptions(),
            // Required for true OS fullscreen (F11 on music detail).
            fullscreenable: true,
            icon: nativeImage.createFromPath(getResourcePath(ResourceName.LOGO_IMAGE)),
        });

        const updateWindowSizeConfig = debounce(() => {
            if (mainWindow.isDestroyed() || mainWindow.isFullScreen()) {
                return;
            }
            // Skip while immersive fullscreen (native or display-bounds fallback).
            if (
                (mainWindow as BrowserWindow & {
                    __immersiveFullscreen?: boolean;
                }).__immersiveFullscreen
            ) {
                return;
            }
            const [wWidth, wHeight] = mainWindow.getSize();
            AppConfig.setConfig({
                "private.mainWindowSize": {
                    width: wWidth,
                    height: wHeight,
                },
            });
        }, 300, {
            leading: false,
            trailing: true,
        });
        mainWindow.on("resize", updateWindowSizeConfig);

        const notifyMainWindowFullScreen = () => {
            if (mainWindow.isDestroyed()) {
                return;
            }
            mainWindow.webContents.send(
                "@shared/utils/main-window-fullscreen-changed",
                mainWindow.isFullScreen(),
            );
        };
        mainWindow.on("enter-full-screen", notifyMainWindowFullScreen);
        mainWindow.on("leave-full-screen", notifyMainWindowFullScreen);

        // Capture F11 in the main process so Chromium cannot swallow it.
        // Renderer only acts when the music detail page is open.
        mainWindow.webContents.on("before-input-event", (event, input) => {
            if (input.type !== "keyDown") {
                return;
            }
            const isF11 =
                input.key === "F11"
                || input.code === "F11"
                || (input as { keyCode?: string }).keyCode === "F11";
            if (!isF11) {
                return;
            }
            event.preventDefault();
            if (mainWindow.isDestroyed()) {
                return;
            }
            mainWindow.webContents.send("@shared/utils/main-window-f11");
        });

        // 2. 加载主界面
        WindowManager.mainWindow = mainWindow;
        hardenWindow(mainWindow, MAIN_WINDOW_WEBPACK_ENTRY);
        loadRendererEntry(
            mainWindow,
            MAIN_WINDOW_WEBPACK_ENTRY,
            `/main/musicsheet/${localPluginName}/favorite`,
        ).then(voidCallback);

        // 3. 开发者工具
        if (!app.isPackaged) {
            mainWindow.on("ready-to-show", () => {
                mainWindow.webContents.openDevTools();
            });
        }

        // 4. 主窗口 HTTP hack 逻辑
        mainWindow.webContents.session.webRequest.onBeforeSendHeaders(
            (details, callback) => {
                try {
                    const url = new URL(details.url);
                    const setHeadersOptions = url.searchParams.get("_setHeaders");
                    if (
                        !["https:", "http:"].includes(url.protocol)
                        || !setHeadersOptions
                        || setHeadersOptions.length > 64 * 1024
                        || (
                            details.webContentsId !== undefined
                            && details.webContentsId !== mainWindow.webContents.id
                        )
                    ) {
                        throw new Error("No Need To Hack");
                    }
                    const originalRequestHeaders = details.requestHeaders ?? {};
                    const decodedHeaders = JSON.parse(
                        decodeURIComponent(setHeadersOptions),
                    ) as Record<string, unknown>;
                    if (
                        !decodedHeaders
                        || typeof decodedHeaders !== "object"
                        || Array.isArray(decodedHeaders)
                        || Object.keys(decodedHeaders).length > 64
                    ) {
                        throw new Error("Invalid Header Payload");
                    }
                    const requestHeaders: Record<string, string> = {};
                    for (const [name, value] of Object.entries(originalRequestHeaders)) {
                        requestHeaders[name.toLocaleLowerCase()] = value;
                    }
                    const forbiddenHeaders = new Set([
                        "host",
                        "content-length",
                        "connection",
                        "transfer-encoding",
                        "upgrade",
                    ]);
                    for (const [rawName, value] of Object.entries(decodedHeaders)) {
                        const name = rawName.toLocaleLowerCase();
                        if (
                            !/^[a-z0-9-]{1,64}$/.test(name)
                            || forbiddenHeaders.has(name)
                            || name.startsWith("proxy-")
                            || name.startsWith("sec-")
                            || typeof value !== "string"
                            || value.length > 8192
                            || /[\r\n]/.test(value)
                        ) {
                            throw new Error("Invalid Header");
                        }
                        requestHeaders[name] = value;
                    }
                    callback({
                        requestHeaders,
                    });
                } catch {
                    callback({
                        requestHeaders: details.requestHeaders,
                    });
                }
            },
        );

        mainWindow.on("close", (e) => {
            if (process.platform === "win32" && AppConfig.getConfig("normal.closeBehavior") === "minimize") {
                e.preventDefault();
                mainWindow.hide();
                mainWindow.setSkipTaskbar(true);
            }
        });

        // 5. 鏇存柊thumbbar
        ThumbBarUtil.setThumbBarButtons(mainWindow, false);
        // 6. 鍙戝嚭淇″彿
        this.emit("WindowCreated", {
            windowName: "main",
            browserWindow: mainWindow,
        });
    }

    public showMainWindow() {
        if (!WindowManager.mainWindow || WindowManager.mainWindow.isDestroyed()) {
            this.createMainWindow();
        }

        const mainWindow = WindowManager.mainWindow;
        if (!mainWindow) {
            return;
        }

        if (mainWindow.isMinimized()) {
            mainWindow.restore();
        } else if (mainWindow.isVisible()) {
            mainWindow.focus();
        } else {
            mainWindow.show();
        }
        mainWindow.moveTop();
        mainWindow.setSkipTaskbar(false);

        if (process.platform === "win32") {
            const appState = messageBus.getAppState();
            ThumbBarUtil.setThumbBarButtons(
                mainWindow,
                isPlaybackActive(appState.playerState),
            );
        }
    }

    public closeMainWindow() {
        WindowManager.mainWindow?.close();
        WindowManager.mainWindow = null;
    }

    /**************************** Lyric Window ***************************/
    private static lyricWindowDefaultSize: ICommon.ISize = {
        width: 940,
        height: 180,
    };
    private static lyricWindowMinSize: ICommon.ISize = {
        width: 480,
        height: 132,
    };
    private static lyricWindowMaxSize: ICommon.ISize = {
        width: Infinity,
        height: Infinity,
    };

    private formatLyricWindowSize(width?: number, height?: number): ICommon.ISize {
        return {
            width: Math.min(Math.max(width ?? Infinity, WindowManager.lyricWindowMinSize.width), WindowManager.lyricWindowMaxSize.width),
            height: Math.min(Math.max(height ?? Infinity, WindowManager.lyricWindowMinSize.height), WindowManager.lyricWindowMaxSize.height),
        };
    }

    private repaintTransparentWindow(window: BrowserWindow) {
        if (process.platform !== "win32" || window.isDestroyed()) {
            return;
        }

        const bounds = window.getBounds();
        const [minWidth] = window.getMinimumSize();
        const [maxWidth] = window.getMaximumSize();
        const canGrow = maxWidth === 0 || bounds.width < maxWidth;
        const canShrink = bounds.width > minWidth;
        const width = canGrow ? bounds.width + 1 : (canShrink ? bounds.width - 1 : bounds.width);

        if (width === bounds.width) {
            return;
        }

        // Windows transparent windows can retain a stale edge until DWM recomposites them.
        this.repaintingTransparentWindows.add(window);
        try {
            window.setBounds({
                ...bounds,
                width,
            }, false);
            window.setBounds(bounds, false);
        } finally {
            setTimeout(() => {
                this.repaintingTransparentWindows.delete(window);
            }, 50);
        }
    }

    private repaintTransparentWindowAfterShow(window: BrowserWindow) {
        setTimeout(() => {
            this.repaintTransparentWindow(window);
        }, 0);
    }

    private syncLyricWindowZOrder(window: BrowserWindow): boolean {
        try {
            const shouldStayOnTop = !(
                isFullscreenApplicationRunning()
                || isFullscreenForegroundWindow()
            );
            if (window.isAlwaysOnTop() !== shouldStayOnTop) {
                window.setAlwaysOnTop(shouldStayOnTop);
            }
            return true;
        } catch (error) {
            logger.logError("Failed to update desktop lyric window z-order", toError(error));
            return false;
        }
    }

    private stopLyricWindowZOrderMonitor() {
        if (this.lyricWindowZOrderMonitor) {
            clearInterval(this.lyricWindowZOrderMonitor);
            this.lyricWindowZOrderMonitor = null;
        }
    }

    private startLyricWindowZOrderMonitor(window: BrowserWindow) {
        this.stopLyricWindowZOrderMonitor();
        if (process.platform !== "win32" || !this.syncLyricWindowZOrder(window)) {
            return;
        }
        this.lyricWindowZOrderMonitor = setInterval(() => {
            if (window.isDestroyed() || !this.syncLyricWindowZOrder(window)) {
                this.stopLyricWindowZOrderMonitor();
            }
        }, WindowManager.lyricWindowZOrderPollInterval);
        this.lyricWindowZOrderMonitor.unref();
    }

    private showTransparentLyricWindow(window: BrowserWindow) {
        if (process.platform === "win32") {
            this.syncLyricWindowZOrder(window);
        }
        window.setBackgroundColor("#00000000");
        window.show();
        this.repaintTransparentWindowAfterShow(window);
    }


    private createLyricWindow() {
        const initPosition = AppConfig.getConfig("private.lyricWindowPosition");
        const initSize = AppConfig.getConfig("private.lyricWindowSize");
        const display = initPosition
            ? screen.getDisplayNearestPoint(initPosition)
            : screen.getPrimaryDisplay();

        WindowManager.lyricWindowMaxSize.width = display.workArea.width;
        WindowManager.lyricWindowMaxSize.height = display.workArea.height;

        const isLegacyBubbleWindow = !!initSize && initSize.width <= 560 && initSize.height <= 180;
        const isLegacyDefaultWindow = !!initSize
            && ((initSize.width === 900 && initSize.height === 180)
                || (initSize.width === 810 && initSize.height === 198)
                || (initSize.width === 729 && initSize.height === 218)
                || (initSize.width === 583 && initSize.height === 218));
        const preferredSize = (isLegacyBubbleWindow || isLegacyDefaultWindow)
            ? WindowManager.lyricWindowDefaultSize
            : (initSize ?? WindowManager.lyricWindowDefaultSize);
        let {
            width,
            height,
        } = this.formatLyricWindowSize(preferredSize.width, preferredSize.height);

        const lyricWindow = new BrowserWindow({
            height,
            width,
            x: initPosition?.x,
            y: initPosition?.y,
            transparent: true,
            backgroundColor: "#00000000",
            webPreferences: {
                preload: LRC_WINDOW_PRELOAD_WEBPACK_ENTRY,
                nodeIntegration: false,
                nodeIntegrationInWorker: false,
                contextIsolation: true,
                webSecurity: true,
                allowRunningInsecureContent: false,
                sandbox: true,
                webviewTag: false,
                navigateOnDragDrop: false,
            },
            minWidth: WindowManager.lyricWindowMinSize.width,
            minHeight: WindowManager.lyricWindowMinSize.height,
            maxWidth: WindowManager.lyricWindowMaxSize.width,
            maxHeight: WindowManager.lyricWindowMaxSize.height,
            // Keep custom resize available while removing the Windows DWM non-client
            // frame/shadow that can appear as a black edge on transparent windows.
            resizable: true,
            frame: false,
            show: false,
            paintWhenInitiallyHidden: true,
            skipTaskbar: true,
            alwaysOnTop: true,
            thickFrame: false,
            hasShadow: false,
            roundedCorners: false,
            icon: nativeImage.createFromPath(getResourcePath(ResourceName.LOGO_IMAGE)),
        });

        lyricWindow.setMaximumSize(WindowManager.lyricWindowMaxSize.width, WindowManager.lyricWindowMaxSize.height);
        this.startLyricWindowZOrderMonitor(lyricWindow);

        WindowManager.lrcWindow = lyricWindow;
        hardenWindow(lyricWindow, LRC_WINDOW_WEBPACK_ENTRY);
        // and load the index.html of the app.
        loadRendererEntry(lyricWindow, LRC_WINDOW_WEBPACK_ENTRY).then(voidCallback);

        if (!app.isPackaged) {
            // Open the DevTools.
            lyricWindow.webContents.openDevTools();
        }

        const savePositionConfig = () => {
            if (!lyricWindow || lyricWindow.isDestroyed()) {
                return;
            }
            if (this.repaintingTransparentWindows.has(lyricWindow)) {
                return;
            }
            const [x, y] = lyricWindow.getPosition();
            AppConfig.setConfig({
                "private.lyricWindowPosition": {
                    x,
                    y,
                },
            });
        };
        const updatePositionConfig = debounce(savePositionConfig, 300, {
            leading: false,
            trailing: true,
        });
        const saveSizeConfig = () => {
            if (!lyricWindow || lyricWindow.isDestroyed()) {
                return;
            }
            if (this.repaintingTransparentWindows.has(lyricWindow)) {
                return;
            }
            const [wWidth, wHeight] = lyricWindow.getSize();
            // 确保值是有效的数字
            if (typeof wWidth === "number" && typeof wHeight === "number" &&
                !isNaN(wWidth) && !isNaN(wHeight) &&
                isFinite(wWidth) && isFinite(wHeight)) {
                AppConfig.setConfig({
                    "private.lyricWindowSize": {
                        width: Math.round(wWidth),
                        height: Math.round(wHeight),
                    },
                });
            }
        };
        const updateSizeConfig = debounce(saveSizeConfig, 300, {
            leading: false,
            trailing: true,
        });
        let lyricWindowShown = false;
        let showFallbackTimer: NodeJS.Timeout | null = null;
        const clearShowFallbackTimer = () => {
            if (showFallbackTimer) {
                clearTimeout(showFallbackTimer);
                showFallbackTimer = null;
            }
        };
        const showReadyLyricWindow = () => {
            if (lyricWindowShown || lyricWindow.isDestroyed()) {
                return;
            }
            if (this.auxiliaryWindowVisibilityBeforeImmersive) {
                this.auxiliaryWindowVisibilityBeforeImmersive.lyric = true;
                return;
            }
            lyricWindowShown = true;
            this.showTransparentLyricWindow(lyricWindow);
        };
        lyricWindow.on("close", () => {
            clearShowFallbackTimer();
            updatePositionConfig.cancel();
            savePositionConfig();
            updateSizeConfig.cancel();
            saveSizeConfig();
        });
        lyricWindow.on("closed", () => {
            clearShowFallbackTimer();
            updatePositionConfig.cancel();
            updateSizeConfig.cancel();
            this.stopLyricWindowZOrderMonitor();
            WindowManager.lrcWindow = null;
        });


        lyricWindow.on("resize", () => {
            const [wWidth, wHeight] = lyricWindow.getSize();
            width = wWidth;
            height = wHeight;
            updateSizeConfig();
        });

        lyricWindow.on("move", updatePositionConfig);
        if (process.platform !== "darwin") {
            lyricWindow.on("moved", savePositionConfig);
        }
        // 初始化设置
        showFallbackTimer = setTimeout(showReadyLyricWindow, 2000);
        lyricWindow.once("ready-to-show", async () => {
            clearShowFallbackTimer();
            const position = AppConfig.getConfig("private.lyricWindowPosition");
            if (position) {
                this.normalizeWindowPosition(lyricWindow, position, async (position) => {
                    AppConfig.setConfig({
                        "private.lyricWindowPosition": position,
                    });
                });
            }

            const lockState = AppConfig.getConfig("lyric.lockLyric");

            if (lockState) {
                lyricWindow.setIgnoreMouseEvents(true, {
                    forward: true,
                });
            }

            showReadyLyricWindow();
        });

        this.emit("WindowCreated", {
            windowName: "lyric",
            browserWindow: lyricWindow,
        });
    }


    public showLyricWindow() {
        if (this.auxiliaryWindowVisibilityBeforeImmersive) {
            this.auxiliaryWindowVisibilityBeforeImmersive.lyric = true;
            AppConfig.setConfig({
                "lyric.enableDesktopLyric": true,
            });
            return;
        }

        const needsCreate = !WindowManager.lrcWindow || WindowManager.lrcWindow.isDestroyed();
        if (needsCreate) {
            this.createLyricWindow();
        }

        const lrcWindow = WindowManager.lrcWindow;
        if (!lrcWindow) {
            return;
        }

        if (!needsCreate) {
            this.showTransparentLyricWindow(lrcWindow);
        }
        AppConfig.setConfig({
            "lyric.enableDesktopLyric": true,
        });

    }

    public closeLyricWindow() {
        if (this.auxiliaryWindowVisibilityBeforeImmersive) {
            this.auxiliaryWindowVisibilityBeforeImmersive.lyric = false;
        }
        this.stopLyricWindowZOrderMonitor();
        const lyricWindow = WindowManager.lrcWindow;
        if (lyricWindow && !lyricWindow.isDestroyed()) {
            const [x, y] = lyricWindow.getPosition();
            AppConfig.setConfig({
                "private.lyricWindowPosition": {
                    x,
                    y,
                },
            });
            lyricWindow.close();
        }
        WindowManager.lrcWindow = null;
        AppConfig.setConfig({
            "lyric.enableDesktopLyric": false,
        });
    }

    /**************************** MiniMode Window ***************************/
    private createMiniModeWindow() {
        // Create the browser window.
        const width = 428;
        const height = 104;
        const initPosition = AppConfig.getConfig("private.minimodeWindowPosition");

        const miniWindow = new BrowserWindow({
            height,
            width,
            x: initPosition?.x,
            y: initPosition?.y,
            webPreferences: {
                preload: MINIMODE_WINDOW_PRELOAD_WEBPACK_ENTRY,
                nodeIntegration: false,
                nodeIntegrationInWorker: false,
                contextIsolation: true,
                webSecurity: true,
                allowRunningInsecureContent: false,
                sandbox: true,
                webviewTag: false,
                navigateOnDragDrop: false,
            },
            show: false,
            resizable: false,
            frame: false,
            skipTaskbar: true,
            alwaysOnTop: true,
            transparent: true,
            backgroundColor: "#00000000",
            maximizable: false,
            minimizable: false,
            fullscreenable: false,
        });

        WindowManager.miniModeWindow = miniWindow;
        hardenWindow(miniWindow, MINIMODE_WINDOW_WEBPACK_ENTRY);
        // and load the index.html of the app.
        loadRendererEntry(miniWindow, MINIMODE_WINDOW_WEBPACK_ENTRY).then(voidCallback);

        if (!app.isPackaged) {
            miniWindow.on("ready-to-show", () => {
                // Open the DevTools.
                miniWindow.webContents.openDevTools();
            });
        }

        const savePositionConfig = () => {
            if (miniWindow.isDestroyed()) {
                return;
            }
            const [x, y] = miniWindow.getPosition();
            AppConfig.setConfig({
                "private.minimodeWindowPosition": {
                    x: Math.round(x),
                    y: Math.round(y),
                },
            });
        };
        const updatePositionConfig = debounce(savePositionConfig, 300, {
            leading: false,
            trailing: true,
        });
        miniWindow.on("close", () => {
            updatePositionConfig.cancel();
            savePositionConfig();
        });
        miniWindow.on("closed", () => {
            updatePositionConfig.cancel();
            WindowManager.miniModeWindow = null;
        });
        miniWindow.on("move", updatePositionConfig);
        if (process.platform !== "darwin") {
            miniWindow.on("moved", savePositionConfig);
        }

        miniWindow.once("ready-to-show", () => {
            const position = AppConfig.getConfig("private.minimodeWindowPosition");
            if (position) {
                this.normalizeWindowPosition(miniWindow, position, async (position) => {
                    AppConfig.setConfig({
                        "private.minimodeWindowPosition": position,
                    });
                });
            }

        });
        this.emit("WindowCreated", {
            windowName: "minimode",
            browserWindow: miniWindow,
        });
    }

    public showMiniModeWindow() {
        if (this.auxiliaryWindowVisibilityBeforeImmersive) {
            this.auxiliaryWindowVisibilityBeforeImmersive.minimode = true;
            AppConfig.setConfig({
                "private.minimode": true,
            });
            return;
        }

        if (!WindowManager.miniModeWindow) {
            this.createMiniModeWindow();
        }

        const miniWindow = WindowManager.miniModeWindow;
        if (!miniWindow) {
            return;
        }

        if (miniWindow.isMinimized()) {
            miniWindow.restore();
        } else if (miniWindow.isVisible()) {
            miniWindow.focus();
        } else {
            miniWindow.show();
        }
        miniWindow.moveTop();
        miniWindow.setSkipTaskbar(true);
        AppConfig.setConfig({
            "private.minimode": true,
        });
    }


    public closeMiniModeWindow() {
        if (this.auxiliaryWindowVisibilityBeforeImmersive) {
            this.auxiliaryWindowVisibilityBeforeImmersive.minimode = false;
        }
        WindowManager.miniModeWindow?.close();
        WindowManager.miniModeWindow = null;
        AppConfig.setConfig({
            "private.minimode": false,
        });
        // Closing mini mode should restore the main window. Do this in the main
        // process: the mini renderer may also send show-main-window, but that
        // IPC is rejected once the mini window reference is cleared / destroyed.
        this.showMainWindow();
    }

    private normalizeWindowPosition(window: BrowserWindow, position: ICommon.IPoint, onNormalized: (position: ICommon.IPoint) => void) {
        const currentDisplayBounds =
            screen.getDisplayNearestPoint(position).bounds;
        const windowBounds = window.getBounds();
        // 如果窗口完全在屏幕外，重置位置
        const [left, top, right, bottom] = [
            position.x,
            position.y,
            position.x + windowBounds.width,
            position.y + windowBounds.height,
        ];
        let needMakeup = false;
        if (left > currentDisplayBounds.x + currentDisplayBounds.width) {
            position.x =
                currentDisplayBounds.x + currentDisplayBounds.width - windowBounds.width;
            needMakeup = true;
        } else if (right < currentDisplayBounds.x) {
            position.x = currentDisplayBounds.x;
            needMakeup = true;
        }
        if (top > currentDisplayBounds.y + currentDisplayBounds.height) {
            position.y =
                currentDisplayBounds.y + currentDisplayBounds.height - windowBounds.height;
            needMakeup = true;
        } else if (bottom < currentDisplayBounds.y) {
            position.y = currentDisplayBounds.y;
            needMakeup = true;
        }
        window.setPosition(position.x, position.y, false);
        if (needMakeup) {
            onNormalized(position);
        }
    }
}


export default new WindowManager();
