import { defaultFont } from "@/common/constant";
import { IAppConfig } from "@/types/app-config";

const _defaultAppConfig: IAppConfig =  {
    "$schema-version": 1,
    "playMusic.whenQualityMissing": "lower",
    "playMusic.defaultQuality": "flac",
    "playMusic.clickMusicList": "replace",
    "playMusic.caseSensitiveInSearch": false,
    "playMusic.newSheetDefaultSort": "time",
    "playMusic.playError": "skip",
    "playMusic.whenDeviceRemoved": "play",
    "playMusic.wasapiExclusive": false,
    "normal.taskbarThumb": "window",
    "normal.closeBehavior": "minimize",
    "normal.checkUpdate": true,
    "normal.autoLoadMore": true,
    "normal.maxHistoryLength": 30,
    "download.defaultQuality": "flac",
    "download.whenQualityMissing": "lower",
    "download.writeMetadata": true,
    "download.writeMetadataCover": true,
    "download.writeMetadataLyric": true,
    "download.downloadLyricFile": false,
    "download.lyricFileFormat": "lrc",
    "download.lyricOrder": ["romanization", "original", "translation"],
    "download.enableWordByWordLyric": false,
    "download.fileNamingType": "preset",
    "download.fileNamingPreset": "title-artist",
    "download.fileNamingCustom": "{title}-{artist}",
    "download.fileNamingMaxLength": 200,
    "lyric.enableDesktopLyric": false,
    "lyric.lockLyric": false,
    "lyric.desktopLyricCenter": false,
    "lyric.fontData": defaultFont,
    "lyric.fontColor": "#fff",
    "lyric.applyFontColorOnlyToPlayedLines": false,
    "lyric.fontSize": 24,
    "lyric.inactiveBrightness": 0.35,
    "lyric.showTranslation": false,
    "lyric.showRomanization": false,
    "shortCut.enableLocal": true,
    "shortCut.enableGlobal": false,
    "download.concurrency": 5,
    "normal.musicListColumnsShown": [],
    "backup.resumeBehavior": "overwrite",
    "localMusic.watchDir": [],
    "normal.language": "zh-CN",
    "normal.uiStyle": "glass",
    "normal.detailAutoHideMusicBar": false,
    "private.lyricWindowSize": {
        width: 940,
        height: 180,
    },
};


export default _defaultAppConfig;
